name: Display Name on Push

on:
  push:
    branches:
      - main

jobs:
  display_name:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run Bash Script
      run: |
        docker run --rm ubuntu:latest bash -c 'echo "Danylo" && echo "Drozdov"'
